---
title: "Получение сведений о системе"
format: 
    md:
        output-file: README.md
---

# Лабораторные работы по дисципоине "Средства аутентификации и защиты от несанкционированного доступа"

# Список выполненных лабораторных работ:

## 1. Получение сведений о системе
# Получение сведений о системе

## Цель работы

Получить сведения об используемой системе

## Исходные данные

1. Ноутбук Asus

2. Windows 11

## План

1. Ввод команд в эмулятор терминала

2. Анализ данных

## Ход работы

1. Затем получим сведения о версии ядра:

```{PowerShell}
winver
```

В результате выполнения данной команды была получена версия ядра - 22H2(сборка ОС 22621.1265)

2. Далее можно получить сведения о процессоре:

```{PowerShell}
Get-WmiObject win32_Processor
```

```{PowerShell}
WMIC CPU Get DeviceID,NumberOfCores,NumberOfLogicalProcessors
```

Было определено, что используемый процессор - четырехъядерный и восьмипоточный Intel(R) Core(TM) i5-1035G1

3. Далее получим последние 30 строк логов системы:

```{PowerShell}
Get-EventLog -LogName 'system' -Newest 30
```

## Оценка результата

В результате лабораторной работы была получена базовая информация об используемой системе.

## Вывод

Таким образом. мы научились, используя команды Windows, получать сведения о системе.